# Namespace where kubernetes-tagger is installed
# namespace: "kube-system"

# Kubernetes configuration file
# kubeconfig: "~/.kube/config"

# Server listener address
# address: :8085

# Log level
loglevel: debug

# Log format
# logformat: json

# Kubernetes provider
provider: aws

# AWS configuration
aws:
  # Region
  region: eu-west-3

# Rules to add / delete tags
rules:
  # Rule definition add value hardcoded
  - tag: tag-hardcoded
    action: delete
  - tag: namespace
    query: service.namespace
    action: add
  - tag: name
    query: service.name
    action: add
  - tag: chart
    query: service.labels.chart
    action: add
  # Rule definition add value from query
  - tag: tag-query
    query: persistentvolume.phase
    action: add
  # Rule definition with condition
  - tag: tag-condition
    query: persistentvolume.name
    action: add
    when:
      - condition: persistentvolume.phase
        value: Bound
        operator: Equal
  # Rule definition delete tag
  - tag: tag-to-be-deleted
    action: delete
